### PR TITLE
refactor(popover): add example with no header, refactor css a little, add some a11y attributes

### PR DESCRIPTION
**Pull request by mcoker**
fixes https://github.com/patternfly/patternfly-next/issues/834

### CODE REVIEW

**Comment by matthewcarleton** [comment]
looks good! I ran this through voiceover and noticed that the examples with header announce the entirety of the popover header/content but the example with no header just announces the `aria-label` on the popover.  This looks like it's caused by `aria-labelledby` vs `aria-label`
We can add `aria-describedby` on the popover to fix this. My question is do we add it for just the header-less examples or all of them for consistency?

**Comment by michael-coker** [comment]
Thanks @matthewcarleton! I'm a little confused as to when to use `aria-describedby`. The examples I've read indicate that it isn't necessarily the body of the popover, but a longer description of what the popover is. Maybe those are the same thing?

**Comment by matthewcarleton** [comment]
@michael-coker ya good point. I'd expect the same experience with/without the header but I'm not sure in our case if the description would be the same as the body or not. It depends if the expectation from a screen reader is to then continue to read the content after they've had the description announced. I'd assume they'd only want the content announced and not a description of it, but I think we'd have to do a bit more research to really know for sure.

**Comment by mcoker** [comment]
@matthewcarleton I compared the popover to the modal, and I believe their accessibility attributes should be the same. Each of the modal examples have `aria-describedby` that points to the body of the modal, so I added those here. Now VO reads the entire contents of the popover in all of the examples. However, another thing I noticed (that's present in the header-less modal example, too) is that the close button isn't read by the screenreader when `aria-label` is used on the parent.

**Comment by matthewcarleton** [comment]
screen shot 2018-11-05 at 9 53 23 am
hmmm, this is what I hear with VO. Is it the same for you?

**Comment by jgiardino** [comment]
These updates match what I'd expect, which is based on the documentation provided here: https://www.w3.org/TR/wai-aria-practices-1.1/examples/dialog-modal/dialog.html

I also consider popovers and modals to be similar enough to have the same keyboard and screen reader experience.

I'm also a little confused by `aria-describedby`, but until we have an interactive JS implementation, it will be hard to judge whether we should keep this or not. So for now, I'd say lets keep it, and we can later decide if it hurts or helps the experience. I did come across [this modal example](https://github.com/edenspiekermann/a11y-dialog) referenced on [inclusive-components.design](https://inclusive-components.design/menus-menu-buttons/#inclusivemenubuttonongithub), which does use `aria-describedby`. I tested this in VO, and it works great.

When reviewing our popovers and modals in VO, I found that I'm not able to access anything except the title and close button, which I thought was odd. I found [this modal example](https://github.com/gdkraus/accessible-modal-dialog) which talks about adding `role="document"` to enable access to dialog contents in NVDA. Maybe a similar thing is happening in VO? On the other hand, our implementation is really similar to the one I mentioned above, and it works as expected. I'm not able to pinpoint where the difference might be (other than one is fully working and ours is static). 

I didn't notice the behavior that @matthewcarleton described.

**Comment by matthewcarleton** [comment]
Merging this with the effort of a11y moving to a new issue because this also affects modal.

**Pull request merged**
