### PR TITLE
fix(dropdown): make the dropdown menu appear on top of tabs

### LINKED ISSUE #1668: Dropdown and tabs z-index issue
When the Dropdown menu is overlaying a tab component, the menu is shown behind the tab which looks off.

Looking at the css, it looks like the `z-index` of tab is bigger than the menu what causes this issue.

Related to https://github.com/patternfly/patternfly-react/issues/1636

### PR DESCRIPTION
**Pull request by boaz0**
fixes #1668

### CODE REVIEW

**Comment by boaz0** [comment]
closing in favor of #1700

**Comment by mcoker** [comment]
@boaz0 do you want to reopen this? Looks like @christiemolloy had a typo in #1700, it doesn't address this z-index issue.

**Comment by boaz0** [comment]
ping

**Comment by christiemolloy** [comment]
hey @boaz0 I was talking with @mcoker about investigating a method to how we order components across the system, because there are other instances of this problem occurring, i.e. the select and options menu have a z-index problem also, and there are z-index's on many other components. Not sure if you want to investigate more into this, otherwise we are happy to.

**Pull request closed without merging**
