### PR TITLE
Fix background image clipping when resizing in Chrome

### PR DESCRIPTION
**Pull request by andybraren**

### CODE REVIEW

**Comment by andybraren** [comment]
As mentioned here: https://github.com/patternfly/patternfly-next/issues/323#issuecomment-413279848

**Comment by andresgalante** [comment]
Fantastic, thanks @andybraren for looking into this :)

**Comment by matthewcarleton** [comment]
I'm ok with this. Maybe instead of leaving it empty just give it a value. 120% should do it according to : https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/width#filter
What do you think @andresgalante

**Comment by andresgalante** [comment]
@andybraren sorry, I merged it and then tested it again and noticed that the image doesn't change size. Do you think you can look a bit more into this and try to fix it?

**Comment by andybraren** [comment]
@matthewcarleton Unfortunately setting the width to 120% makes the clipping behavior return in Chrome.

**Comment by dmiller9911** [comment]
@andresgalante @matthewcarleton  out of curiosity why is an image filter being used? Is it doing more than adding a black overlay too it with a certain opacity? Could the same be achieved with the example below?
```css
.pf-c-background-image:after {
  top: 0;
  right: 0;
  left: 0;
  bottom: 0;
  position: absolute;
  background-color: #000;
  opacity: 0.6;
  content: "";
}
```

**Pull request merged**
