### PR TITLE
feat(SwitchToggleCheckMark): Introducing visible check mark for switch input component

### LINKED ISSUE #914: Switch enhancement: visual differentiation for on/off states
Currently, the visual styling of the on/off states of the switch could make it difficult for some users to differentiate the two states.

image

Some ideas of how to address this issue:

1. include some additional indicator that means “on” (similar to [Carbon](http://www.carbondesignsystem.com/components/toggle/code), [Salesforce](https://www.lightningdesignsystem.com/components/checkbox-toggle/), [Ant](https://ant.design/components/switch/))
2. use more of an opposite background color for "off"
3. display a tooltip on hover

### PR DESCRIPTION
**Pull request by jameslau**
## Objective
The switch input toggle component currently does not have an indicator that allows the user to understand the "on/off" states (visual from @jgiardino below).

image

## Implementation

- Inserting a Font Awesome check mark icon for the "on" state.
- Set check mark to `display: none;` on "off" state.
- via @jgiardino 
  -  > For the disabled version in the on state, should we also include the checkmark in that one, too? 
  -  Added check mark to disabled mode.
  - screen shot 2019-01-09 at 2 39 46 pm
- ` /* stylelint-disable-next-line */` has been added in order to enable nesting to third level for specific element property changes. As of right now, the PF linter does not allow beyond 2 levels of nested properties.
  

fixes #914.

### CODE REVIEW

**Comment by jgiardino** [comment]
Great job with this one, @jameslau!

As for whether this should be used for only specific use cases, I'd defer to @mcarrano and @mceledonia on that one. I do agree that it's only required for the switch without the label, but don't have an opinion on whether that's the only time it should be used.

If we do decide to only have it in the "Switch No Label" example, we should add some documentation to that example that explains the purpose of including it, for example:

> When using a switch with a label, the label should change to indicate the current state of the switch. When using a switch without a label, an icon should be included in the toggle that displays during the "On" state to provide additional visual differentiation between the "On" and "Off" states.

**Comment by jameslau** [comment]
Hi @mcarrano, I can take a second look at the switch component and make those changes. I must of misread your comment from #914:

> Including the checkmark in both _**active and disabled**_ states definitely makes sense. @mceledonia can you make that update and we can move this along?

@jgiardino, should I add that copy to the PF-next site?

**Comment by jgiardino** [comment]
@jameslau I would only add that copy to the "Switch No Label" example if the designers confirm that the check should only show in that example.

**Comment by mcarrano** [comment]
This all makes sense to me @jameslau and @jgiardino .  Yes, I expect that the checkmark icon is only used when there is no label.

**Pull request closed without merging**
