### PR TITLE
fix(login): fix a11y

### LINKED ISSUE #1907: Login: Elements must have sufficient color contrast
This is one of only **two** remaining color contrast issues! It's for login, details from the a11y audit below. The other error in the screenshot is already captured in a separate issue.

Screen Shot 2019-06-06 at 9 20 35 PM

It's basically those three links Terms of Use, Help, and Privacy Policy. The axe browser extension is flagging issues with other text on the page also, but I'm not as worried about that as I am getting the automated tooling to a point where we are free of errors. 

Screen Shot 2019-06-06 at 9 24 10 PM

### PR DESCRIPTION
**Pull request by christiemolloy**
fixes #1907 

unsets the link color text so that its white. Looks like even when its blue at a max-width of "xl" it still doesnt pass the color-contrast test, so I made it white at all sizes @mceledonia is this ok?

### CODE REVIEW

**Comment by mcoker** [comment]
FWIW, these links used to be white, then we made them the normal link color in https://github.com/patternfly/patternfly-next/pull/1281/files#diff-85d2441dd6ceb0f491290b7c882e0547L72

**Comment by christiemolloy** [comment]
@mcoker Are you suggesting that we add that variable back in rather than "unsetting" the color?

**Comment by mcoker** [comment]
If we want the links to be white, I think we should. But I think the reason we changed them from white to blue initially is because it isn't clear that they're links when they're white.

**Comment by christiemolloy** [comment]
From what I can see, to pass a11y violation, the background either needs to be a solid color, or the links need to be white, unless @mceledonia you want to try test another color -- its just hard because the background behind the links changes at every size.

**Comment by christiemolloy** [comment]
@mceledonia do you have any input here. Basically to remove a11y violation we need to change the background gradient, or change the color of the links to white.

**Comment by mceledonia** [comment]
This shouldn't be an issue with our new login screens with the red hat logo in the background... @kybaker should we move forward with the assumption we will have that (and avoid the a11y issue) or find another fix for this in the short term? I'm ok with the white for now as a temporary measure until we get the new login.

**Comment by kybaker** [comment]
@mceledonia I agree - I think the white is a great temporary solution.

**Pull request merged**
