### PR TITLE
fix(file-upload): removed message container, added form to error example

### PR DESCRIPTION
**Pull request by mcoker**
fixes https://github.com/patternfly/patternfly-next/issues/2797

### CODE REVIEW

**Comment by mcoker** [comment]
@mcarrano it just removes the file message/helper text at the bottom (instructions/error text) from the file upload component and relies on the file upload component being in a form for that helper text, so the helper text comes from the form component instead.

That also means:
* Any updates we make to the form component's helper text (descriptive, error, success, etc) will be available when used with file upload since the file upload is no longer creating its own helper text.
* The text doesn't get a blue overlay when you drag/hover the file upload component, since that text is no longer part of the file upload component.

old:
Screen Shot 2020-03-11 at 2 51 59 PM

new:
Screen Shot 2020-03-11 at 2 50 00 PM

**Comment by mcarrano** [comment]
Sounds good to me. Thanks for the explanation @mcoker !

**Comment by mturley** [comment]
Ah, I'm glad you guys made that change, I forgot to mention I needed to make `.pf-c-file-upload` a div instead of a form in the React component so I could get my FormGroup example to work (React will refuse to let you nest a <form> in another <form>).

**Pull request merged**
