### PR TITLE
refactor(mdx): use gatsby-theme-patternfly-org

### LINKED ISSUE #1966: Tabs Component Link
https://www.patternfly.org/v4/documentation/core/components/tabcontent#documentation

Clicking "Tabs Component" link causes 404 error.

### LINKED ISSUE #2187: Full page previews on surge previews strip query strings from URL
When you click on a full-page preview (for example, any of the page demos here - https://patternfly-next-pr-2186.surge.sh/demos/Page/examples/), the query string is removed from the URL so you end up on `/examples-full/`, which lists all of the examples for that demo.

### PR DESCRIPTION
**Pull request by redallen**
Closes #2187 and closes #1966 by nuclear force.

## Previews
- https://deploy-preview-2242--pf-next.netlify.com/
- https://patternfly-next-pr-2242.surge.sh (PDF links don't work because of surge)

## Changes
- Convert docs to mdx
- Refactor docs to use gatsby-theme-patternfly-org to share configuration with https://github.com/patternfly/patternfly-react/ and https://www.patternfly.org

## Known issues
- HTML code for examples is formatted poorly
- Images don't work in codesandbox links
- `<title>` does not change
- Breaks a11y auditor
- Nav examples and Flex align self examples are not styled the same currently as on pf4.patternfly.org
- Handlebars no longer honors whitespace (spaces) between things. Use `&nbsp;` or margins instead.

### CODE REVIEW

**Comment by christiemolloy** [comment]
Visual issues I'm seeing:

html code not formatted properly
Screen Shot 2019-10-07 at 1 21 09 PM

White background missing
Screen Shot 2019-10-07 at 1 22 00 PM

spacing between examples is missing
Screen Shot 2019-10-07 at 1 25 45 PM

Spacing between form components has been removed which makes it hard to see the space between them
Screen Shot 2019-10-07 at 1 26 57 PM

**Comment by christiemolloy** [comment]
Can we put this grey page in a container with a white background, also looks like the link icon is really large

Screen Shot 2019-10-07 at 1 29 06 PM

**Comment by christiemolloy** [comment]
The styling here looks to have changed alot:

Screen Shot 2019-10-07 at 1 30 21 PM

**Comment by redallen** [comment]
Opened a followup issue #2343 for you Christie!

**Pull request merged**
