### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by rachael-phillips**
Requesting this is added as our issue template.

### CODE REVIEW

**Comment by rachael-phillips** [comment]
Relevant issue #2211

**Comment by rachael-phillips** [comment]
> I think this should be the same as what we settle on for React.

Hi @redallen yes, it will be the same as the React template! Thanks!

**Comment by SpyTec** [comment]
> What is your product and what release version are you targeting?

Release version of my product seems unnecessary. Would be better to ask about a release window since we can't know that from a version.

There's also nothing indicating severity of the issue, if it's blocking or just low priority

**Comment by rachael-phillips** [comment]
@tlabaj do you want me to update this with @SpyTec 's suggestion?

**Pull request closed without merging**
