### PR TITLE
feat(upgrades): Add Upgrade Examples for Cards

### PR DESCRIPTION
**Pull request by mindreeper2420**
This PR adds an upgrade example for those looking to move from PatternFly 3 to PatternFly 4. This particular example demonstrates the differences between Cards in PF3 vs PF4.

related to https://github.com/patternfly/patternfly-next/issues/334

### CODE REVIEW

**Comment by andresgalante** [comment]
Good move on kicking off this! If this will turn to be a dashboard of cards, I'd use the grid instead of the level

**Comment by mindreeper2420** [comment]
@andresgalante good call! I've updated the example to use the grid with gutters, in order to replicate the feel of cards on a dashboard.

**Comment by mindreeper2420** [comment]
@jgiardino @matthewcarleton I've updated the order of examples (PF3 and then PF4), as well as fixed the headers to match the content. I also renamed the upgrade example to be `CardUpgradeExample` to be specific.

**Comment by mindreeper2420** [comment]
Requires that https://github.com/patternfly/patternfly-next/pull/393 be merged and then this PR will need to be rebased properly.

**Comment by jgiardino** [comment]
Since all of my questions are captured in #395, these changes look good to me.

**Comment by dgutride** [comment]
@mindreeper2420  - that PR (393) has been merged - is this one ready to go in?

**Pull request merged**
