### PR TITLE
feat(form demo): create basic form demo

### LINKED ISSUE #262: Simple form demo (featuring basic form components only)
Take the form elements introduced in PR #26 to build a demo to display the elements in a form layout. 

- Button groups
- Tootips
- Helper text
- Delete/remove field (example: 'Source Secret' input looks to be a datalist that can be deleted)
- Ghost button (example: 'Create new secret')
- Input group w/dropdown

Component lifecycle: 
- [ ] Interaction design requirements 
- [x] Visuals 
- [x] First checkpoint complete and approved 
- [ ] CSS 
- [ ] React
- [ ] Second checkpoint complete and approved 

Contacts: 
- IxD 
- Visual: @mceledonia 
- CSS: @mattnolting

### PR DESCRIPTION
**Pull request by mattnolting**
Includes significant updates to form component...

Closes #262

### CODE REVIEW

**Comment by mcarrano** [comment]
This is looking good @mattnolting . Just a couple of questions/comments:

* I get the hand cusor when hovering over all fields except the select list. I expect the I-beam cursor whenever hovering over an element that takes keyboard entry.
* When is the intent of the "X" to the right of some of the fields? Is that intended to be a clear button?

**Comment by mattnolting** [comment]
- Thanks for pointing that out, I'll update!
 - I too am unclear about intent of the **X**, but my assumption is that it REMOVES added fields. I'd expect to see a field reset presented differently. In this case, if my assumption is correct, I should add another field above the input + **X** button as at least one should always be present. What do you think? @mcarrano @mceledonia

**Comment by mattnolting** [comment]
Original form reference:

openshift_form

**Comment by mcarrano** [comment]
Thanks for fixing the cursor issue @mattnolting . I not sure about the X then, either. OK to leave it there for now, but doesn't sound like something that should be part of a basic form. We can address separately.

**Pull request merged**
