### PR TITLE
feat(wizard): add support for finished state

### PR DESCRIPTION
**Pull request by mcoker**
fixes https://github.com/patternfly/patternfly-next/issues/1670

### CODE REVIEW

**Comment by mcoker** [comment]
cc @jschuler

**Comment by mcoker** [comment]
@christiemolloy, @jknilans found a bug where if there is a lot of content in the main section, the footer isn't sticky and the content doesn't scroll. Also fixed that in this PR.

**Comment by christiemolloy** [comment]
@kybaker you requested light grey arrows between list items in the breadcrumb component, do you want to update the color here to match:
Screen Shot 2019-04-01 at 3 32 13 PM

**Comment by christiemolloy** [comment]
@mcoker do you think we need x and y scroll? I think that might be alot for the user on mobile, maybe we could just set it to y, or maybe ask design

**Comment by mcoker** [comment]
@christiemolloy re: overflow, looks like we use `y: auto, x: hidden` almost everywhere else so I think that's ok here, too.

Chatted with @kybaker and we decided to go a darker shade, using `$pf-global--BorderColor--200` (`$pf-color-black-500/#8b8d8f`)

@kybaker can you confirm this looks OK? Updated Wizard and Breadcrumbs.

**Comment by kybaker** [comment]
@christiemolloy @mcoker Looks good to me.

**Pull request merged**
