### PR TITLE
feat(about-modal): tested and debugged about modal

### PR DESCRIPTION
**Pull request by mattnolting**
Resolves #377  

After trying several approaches including using empty grid cells for spacing, I believe this is the simplest approach. Instead of padding on each direct child, this layout leverages a single padding-left value and grid-gap to space items correctly.

DL and button styling is temporary, we can discuss the best approach..

### CODE REVIEW

**Comment by dmiller9911** [comment]
Would this be more of a pattern instead of a demo? Demos to me indicate something that is solely composed of components to demonstrate using them together. The fact that this has its own css and markup makes it seem like something more than a demo.

**Comment by mattnolting** [comment]
@dmiller9911 I'm not entirely sure.. Maybe @dgutride and/or @andresgalante could provide guidance.

**Comment by dmiller9911** [comment]
@mattnolting I thought about this more and it kind of makes sense as a demo as well.

 I am looking at it from more of a React point of view. We as a library might need guidance on whether we should provide this, and and if so what it should be (component or demo)

**Comment by andresgalante** [comment]
The modal box is a component, you'd use it on a demo. @dmiller9911 is right, Demos don't have CSS.

The paddings on the childs were defined by the visual team and they ensure the component looks as they intended, so I'll review review and understand #377 before I come to this one.

**Comment by mindreeper2420** [comment]
the build is passing, but I'm seeing this `sass` error in the console:
screen shot 2018-06-28 at 9 47 30 am

**Pull request closed without merging**
