### PR TITLE
fix(horizontal-nav): change nav-link margin to padding

### LINKED ISSUE #1849: Horizontal Nav items focus border issues
image

image

related: https://github.com/patternfly/patternfly-react/issues/2054

### PR DESCRIPTION
**Pull request by mattnolting**
closes #1849 

- change horizontal nav margin to padding (`.pf-c-page__header` only)

### CODE REVIEW

**Comment by christiemolloy** [comment]
@mattnolting looks like this is a breaking change because of the variables that are being removed, we could keep them in and create an issue to remove them after the breaking change period, or we could just hold off merging this PR

**Comment by mattnolting** [comment]
@christiemolloy I think it's fine to hold off and merge during breaking change period.

**Comment by mattnolting** [comment]
@mcoker @christiemolloy updated

**Comment by mattnolting** [comment]
This isn't necessary to fix focus, rather it's a nice to have

**Pull request closed without merging**
