### PR TITLE
Reduce size of BG image

### PR DESCRIPTION
**Pull request by psav**
As this background should be covered up by content most of the time, a small reduction in quality yields a big reduction in filesize.

### CODE REVIEW

**Comment by mcoker** [comment]
@psav this looks great, thanks! Would you mind also copying this file to `src/patternfly/assets/images` and overwrite the existing `pfbg_2000.jpg` file there, too?

**Comment by psav** [comment]
Sure thing

**Comment by psav** [comment]
I can also do another PR to do the same type of transformation to the smaller size images

**Comment by mcoker** [comment]
@psav that would be great, thanks!

**Pull request merged**
