### PR TITLE
fix(color): updated black global and background global/component vars

### PR DESCRIPTION
**Pull request by mcoker**
fixes https://github.com/patternfly/patternfly-next/issues/2424

## Breaking changes
* `$pf-color-black-200` changes to `#f0f0f0`
* `$pf-color-black-600` changes to `#6a6e73`
* `$pf-global--BackgroundColor--200` changes to `$pf-color-black-200 `
* Removes `$pf-global--BackgroundColor--150` and `$pf-global--BackgroundColor--300`
  * Updated all components that use `$pf-global--BackgroundColor--150` or `$pf-global--BackgroundColor--300` to use  `$pf-global--BackgroundColor--200` instead

### CODE REVIEW

**Comment by mattnolting** [comment]
We should update:
- https://github.com/patternfly/patternfly-next/blob/master/build/gulp/ws-lite.css#L3
- https://github.com/patternfly/patternfly-next/blob/master/build/gulp/ws-lite.css#L67

to `--pf-global--BackgroundColor--200` as well

**Comment by mattnolting** [comment]
Andddd, updated tabs.scss here: https://github.com/patternfly/patternfly-next/pull/2757/files#diff-c8d219328bcd3d467c0732874743859fR32

**Comment by mcoker** [comment]
@mattnolting nice catch! updated.

**Comment by mceledonia** [comment]
Nice! This looks great @mcoker

**Comment by christiemolloy** [comment]
For the review notes, when you say "most likely" maybe it could be more encouraging to say update to use... "can be updated to use BackgroundColor--200, but consult your visual designer first" ... just an idea

> Any references to the variables that were removed should be reviewed, and most likely updated to use --pf-global--BackgroundColor--200/$pf-global--BackgroundColor--200 instead, to align with patternfly's usage of BackgroundColor variables.

**Comment by mcoker** [comment]
@christiemolloy updated

**Pull request merged**
