### PR TITLE
fix(toolbar): remove pf-c-toolbar__pagination from Toolbar

### LINKED ISSUE #1570: Remove classes from the Toolbar Component
In #1482 we removed the styles on the class `.pf-c-toolbar__pagination`, this class is not needed anymore as we just use `.pf-c-pagination` so we can remove it after the breaking change period. 

You'll find it in toolbar-pagination-example and toolbar-expanded-example

### PR DESCRIPTION
**Pull request by boaz0**
closes #1570 

//cc @christiemolloy

### CODE REVIEW

**Comment by christiemolloy** [comment]
Looks good - also note that when we merge #1401 we will need to remove this class from there too.. and potentially others.

**Comment by mcoker** [comment]
@boaz0 looks like you have a conflict. Can you rebase?

**Comment by christiemolloy** [comment]
Closing this as #1627 was just merged that addresses the same issue.

**Comment by boaz0** [comment]
No problem :smile:

**Pull request closed without merging**
