### PR TITLE
fix(login): Replace Login's SVG files with inline FontAwesome SVGs

### LINKED ISSUE #1189: Replace images in login footer with FA icons
We don't have permission to use the images in the login page footer, so we should replace those with FA icons and color them to match the brand color.

### PR DESCRIPTION
**Pull request by andybraren**
Fixes #1189.

This replaces the old brand logo files in the Login component's examples with inlined FontAwesome SVGs instead. Doing so lets us remove 7 old files from `/src/patternfly/assets/images`, which is nice.

FontAwesome's brand icons don't include styling, so I've added the appropriate `fill`, `width`, and `height` properties to achieve parity with what we had.

While working on this PR I noticed that the error state example introduced in #1045 didn't include the updated footer HTML of #1132, so I fixed that too.

### CODE REVIEW

**Comment by matthewcarleton** [comment]
I think there could be some improvements here for a11y. @jgiardino please weigh in if I am missing the mark.

Providing the `<title>` tag should be enough for modern browsers but there are bugs reported in Chrome and firefox. One thing you can do is add an id to the `<title id="uniqueID">` and then reference that id in the aria-labelledby attribute on the `<svg aria-labelledby="uniqueID">`

**Comment by mcoker** [comment]
nice! agreed @matthewcarleton. What do you think about adding `role="img"` per https://css-tricks.com/accessible-svgs/? And I would probably add classes to these and use CSS for `height`, `width`, and `fill`

**Comment by jgiardino** [comment]
I thought the visual design was updated by @mceledonia  to not include text as part of these links, and just show the icon? But I could also be way out of the loop on this one, so I apologize if I'm just kicking up dirt.

Assuming this is the design we're going with...

When I use VO, the first link is announced as:
"link, Google logo Google"

Out of context, I don't think this provides enough meaningful info, and would suggest including additional text like "Log in with Google".

This is also a case where the image is redundant. In this case, best practice is to not provide any labeling for the image if it's going to be repeating by the visible text label. [WebAIM has an article](https://webaim.org/techniques/alttext/) that talks about this relative to `` elements and `alt` text, but I think the same general practice applies to this case.

For these suggestions, the updates would be:
- include additional text like "Log in with Google", as an `aria-label` on the link
- include `aria-hidden` on the `<span class="pf-c-login__main-footer-link-text">` to avoid any weird conflicts in labels
- include `aria-hidden` on the `<svg>` which means the `<title>` could also be removed.

But if we did decide that we don't want to display the text with the icons, I would still be hesitant to do anything but `aria-hidden` on the `<svg>` and `aria-label` on the `<a>`. I don't have JAWS in front of me to test this, but in the past when testing with JAWS, `<svg>` elements were announced as either "image" or "graphic". Whenever we're using icons for button or link labels, I don't think it's important for screen reader users to know that an icon is being used instead of text or along with text. It becomes extra noise and extra elements they have to deal with that provide no meaningful value. 

The only place where I would consider exposing images to screen reader users is in the Content component, where it could be important to know that the contents being announced are in the form of an image, like a diagram.

**Comment by matthewcarleton** [comment]
@jgiardino makes a good point. 
I know with the new login design (#1069) does drop the text from the logos. I'd say since we are moving in that direction anyway we should consider that in this work. 
There's not much need in doing this if it will just change anyway. @rachael-phillips that issue is marked at beta-1, if we are looking to revamp the markup for the login we should move this PR towards that work.

**Comment by mcoker** [comment]
closed in lieu of https://github.com/patternfly/patternfly-next/pull/1281

**Pull request closed without merging**
