### PR TITLE
Example of the PF3/PF4 HTML structure: Modal

### LINKED ISSUE #415: Example of the PF3/PF4  HTML structure: Modal
Create simple HTML files files to show the class structure differences between the modal for PatternFly 3 and PatternFly 4.

PF modal example: https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/modals.html

### PR DESCRIPTION
**Pull request by christiemolloy**
This closes #415 

Compares the Modal in pf3 with the Modal in pf4, leaving out js implementation that allows the modal to "pop up" from a button.

### CODE REVIEW

**Comment by matthewcarleton** [comment]
This looks great! I only wonder if we should have some notes for main differences for pf4? What do you think? That area is a bit of mystery to me.

**Comment by jameslau** [comment]
Hey @christiemolloy, this looks pretty good. I added an empty cell to the bottom because it looked a little off without it. 

re: some notes for main differences for pf4, @matthewcarleton would further detailed notes be added to the same page? I have migration docs that may need the same treatment as well. Let's connect when you and @christiemolloy have the time.

**Comment by christiemolloy** [comment]
@jameslau @matthewcarleton we should discuss that section after break :) and maybe go ahead with what is here now? what do you think?

**Comment by jameslau** [comment]
@christiemolloy @matthewcarleton, I'm up for a discussion! Let me know when.

**Comment by LHinson** [comment]
@christiemolloy +1 

The migration docs need some refinement overall. Let's get the things in flight landed to the best of our ability. We will come back to the larger migration doc strategy and discussion at a later date, when we have a place on the website to actually see this stuff in context.

**Comment by christiemolloy** [comment]
@matthewcarleton just fixed 👍

**Comment by matthewcarleton** [comment]
Merging, @jameslau @christiemolloy we can push out dealing with the notes for now. This is in a good place to go into the workspace 👍

**Pull request merged**
