### PR TITLE
fix(title): enabled long strings to wrap

### PR DESCRIPTION
**Pull request by mcoker**
fixes https://github.com/patternfly/patternfly-next/issues/2661

### CODE REVIEW

**Comment by mcoker** [comment]
@boaz0 can you give me an example? I tried this in both FF and chrome, doesn't overflow.

Screen Shot 2020-02-04 at 3 17 08 PM

**Comment by boaz0** [comment]
Uhh... sorry my mistake. I forgot to mention that if it is inside a `flex layout` it doesn't work.

```
  <div style={{display: 'flex'}}>
  <Title headingLevel="h1" style={{overflowWrap: "break-word"}} size="4xl">
    SuperDuperlooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooongTitle
  </Title>
```

**Comment by mcoker** [comment]
@boaz0 ahh good find, that's due to a flex child's default `min-width` being the width of its contents. We can use `word-break: break-word;` there instead, which is similar and will allow the string to break in a flex child. Updated.

**Pull request merged**
