### PR TITLE
feat(dropdown): Implements search interface for dropdown with many items

### PR DESCRIPTION
**Pull request by thomasmaas**
End objective is to create a Context Selector as described in https://github.com/patternfly/patternfly-next/issues/133. When discussing with @mcoker decided to see if the existing dropdown component can be used.

Started with a basic example of a dropdown with search only using existing PF4 code. Visually this is not optimal but serves a a starting point for further conversation/improvement.

screenshot 2018-12-14 17 03 09

### CODE REVIEW

**Comment by mcarrano** [comment]
@thomasmaas @mcoker The only problem with this is that the Context Selector behaves more like a select list than a dropdown where the the selected value should replace the label of the control. This will reflect the current selected context. So I'm wondering if it makes more sense to build this off of the dropdown select list that @srambach is working on.

**Comment by mcoker** [comment]
@mcarrano thanks, I'm not sure where we were at with the Select dropdown when this issue originally came up, but agreed that this should be built into or from the select component. @srambach do you agree? If so, I think we can move this work over to the select component once that PR is merged.

**Comment by thomasmaas** [comment]
Looking at https://github.com/patternfly/patternfly-next/pull/1096 makes me think the Type-ahead select (single item) fully implements what's needed for the context selector. The only difference is the search input and current selection sharing the same visual spot. But if the current selection is restored when out of focus it could be used as a context selector as is. Am I overlooking something @mcarrano ?

**Comment by mcarrano** [comment]
I agree @thomasmaas . The only issue I see is the Clear button for the type-ahead select. Not sure this makes sense in the context selection use case. Maybe when used as a context selector we would hide that?  @kybaker what do you think? Do we need the context selector to be a unique component or is this just an instance of a Select placed in the masthead?

**Comment by rachael-phillips** [comment]
Hi @thomasmaas , do you have an update on this work?

**Comment by thomasmaas** [comment]
Hi @rachael-phillips, no. Waiting for https://github.com/patternfly/patternfly-next/pull/1096 and a confirmation from @kybaker that it makes sense to use custom select with type ahead for context selector.

**Comment by rachael-phillips** [comment]
Thanks for the update!

**Comment by kybaker** [comment]
@thomasmaas @mcarrano It seems to me that using the select functionality is the simplest solution. However we will need a custom variable for this because of how we want it styles with no white background and white text.

**Comment by matthewcarleton** [comment]
thanks for taking care of this. Because of other another PR being opened to address this being its own component I'm going to close this.

**Pull request closed without merging**
