### PR TITLE
fix(colors): set gold shades according to the visual doc

### LINKED ISSUE #1332: pf-gold color discrepency
A few of the gold shades differ between the visual doc and the color variables file.

### Visuals doc
pf-gold-100:  #fbe8b6
pf-gold-200:  #fadd92
pf-gold-300:  #f9d67a
pf-gold-400:  #dcab56
pf-gold-500:  #ac7f33

### Color Variables
pf-gold-100:  #fbeabc
pf-gold-200:  #f9d67a
pf-gold-300:  #f5c12e
pf-gold-400:  #f0ab00
pf-gold-500:  #b58100

screen shot 2019-01-29 at 11 42 16 am

### PR DESCRIPTION
**Pull request by boaz0**
closes #1332

### CODE REVIEW

**Comment by matthewcarleton** [comment]
thanks @boaz0! We may need to confirm with @mceledonia that these values won't be changed as per @cshinn comment in the issue.

**Comment by mceledonia** [comment]
@matthewcarleton These will be changed, I will create a new set based on the gold we use for alerts. I'll see if I can get that done early today!

**Comment by mceledonia** [comment]
Fixed, new set based around current gold-400, also added more contrast between 100-300.

image

gold-100  -  #F9E0A2
gold-200  -  #F6D173
gold-300  -  #F4C145
gold-400  -  #F0AB00
gold-500  -  #AF7D00

Leave gold-600/700 as they are, not sure what we are going to do with those yet.

FYI:
@matthewcarleton @mcoker @cshinn @gdoyle1 @kybaker

**Comment by cshinn** [comment]
Looks good @mceledonia !

**Pull request merged**
