### PR TITLE
fix(build): move build back to separate component build for correct dist

### PR DESCRIPTION
**Pull request by dgutride**
We need the component structure and sass-variables/patternfly.scss to match what it used to be.  This puts it back and works with the new gatsby config.

### CODE REVIEW

**Comment by dgutride** [comment]
I also copied this over to integr8ly to see if it works there and it's fine on that end, too @redallen .

**Comment by redallen** [comment]
I fixed the watch task to work. Compiling our SASS separately during the watch task has been problematic for hot-reloading, so we've moved back to Gatsby compiling our SASS for now.

**Comment by dgutride** [comment]
Please do not commit static/assets/*, they do not belong in that location in the repo.

**Pull request merged**
