### PR TITLE
fix(build): remove github pages deploy

### PR DESCRIPTION
**Pull request by redallen**
Second attempt to fix the master build since #2160 only partially worked :)

### CODE REVIEW

**Comment by dgutride** [comment]
@redallen  - do we still need the github pages deploy?

**Comment by redallen** [comment]
I believe the gh-pages is what's deployed to pf4.patternfly.org .

**Comment by dgutride** [comment]
The DNS entry points at pf-next.netlify.com - this only pushes to patternfly.org/patternfly-next and I'm pretty sure we don't link to that anywhere.  Can we turn this off and remove any gh deploy settings from this repo?

**Comment by redallen** [comment]
Yep, you're correct! Need reapproval @dgutride .

**Pull request merged**
